"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "es" | "en" | "fr" | "pt"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  es: {
    home: "Inicio",
    about: "Nosotros",
    services: "Servicios",
    contact: "Contacto",
    slogan: "Tu Sueño a Realidad",
    hero_title: "Momentos que perduran para siempre",
    hero_subtitle:
      "Transformamos tus sueños en eventos extraordinarios. Diseñamos experiencias únicas que capturan la esencia de cada celebración.",
    hero_location_message:
      "Sin importar de dónde eres, planeamos tu evento y lo realizamos en El Salvador con la máxima excelencia.",
    hero_cta: "Comienza tu historia",
    hero_cta_secondary: "Descubre nuestros servicios",
    events_social: "Eventos Sociales Exclusivos",
    events_corporate: "Eventos Corporativos de Alto Impacto",
    excellence: "Excelencia en Cada Detalle",
    features_title: "Por qué elegirnos",
    features_subtitle:
      "Transformamos tu visión en una experiencia inolvidable con planificación excepcional y ejecución perfecta",
    feature_1_title: "Experiencia Profesional",
    feature_1_desc: "Años de experiencia creando eventos memorables con atención al detalle y pasión",
    feature_2_title: "Diseño Personalizado",
    feature_2_desc: "Cada evento es único y diseñado específicamente para reflejar tu visión y personalidad",
    feature_3_title: "Coordinación Perfecta",
    feature_3_desc: "Manejo integral de todos los aspectos para que disfrutes sin preocupaciones",
    cta_title: "¿Listo para crear algo extraordinario?",
    cta_subtitle: "Conversemos sobre tu evento y hagamos realidad tu visión",
    cta_button: "Contactar ahora",
    about_hero_title: "Nuestra Historia",
    about_hero_subtitle: "Creando momentos eternos con pasión y dedicación",
    our_story_badge: "Nuestra Historia",
    passion_title: "Nuestra Pasión",
    passion_desc: "Convertir sueños en realidad a través de la planificación meticulosa y la creatividad sin límites",
    no_borders_title: "Sin Fronteras",
    commitment_title: "Nuestro Compromiso Contigo",
    commitment_1_title: "Personalizado",
    commitment_1_desc: "Cada evento diseñado exclusivamente para ti",
    commitment_2_title: "Disponibilidad",
    commitment_2_desc: "Apoyo constante durante todo el proceso",
    commitment_3_title: "Dedicación",
    commitment_3_desc: "Sin límites en la búsqueda de la perfección",
    benefits_title: "El respaldo que necesitas para tu evento perfecto",
    benefit_1_title: "Experiencia Comprobada",
    benefit_1_desc: "Planificadores profesionales con visión internacional y estándares de clase mundial",
    benefit_2_title: "Atención al Detalle",
    benefit_2_desc: "Cada elemento es cuidadosamente seleccionado y coordinado para crear momentos perfectos",
    benefit_3_title: "Ejecución Impecable",
    benefit_3_desc: "Coordinación fluida y profesional para que disfrutes sin preocupaciones",
    story_title: "Cómo nació Eternia",
    story_text:
      "Eternia nació del sueño de crear momentos que transcenden el tiempo. Siempre aspiramos a ser más que organizadores de eventos; queremos ser creadores de experiencias inolvidables. Cada celebración es una oportunidad única para transformar visiones en realidad, capturando la esencia de los momentos más significativos y convirtiéndolos en recuerdos eternos.",
    values_title: "Nuestros Valores",
    value_1: "Excelencia sin límites",
    value_2: "Creatividad e innovación",
    value_3: "Dedicación personalizada",
    value_4: "Compromiso inquebrantable",
    services_hero_title: "Nuestros Servicios",
    services_hero_subtitle: "Eventos diseñados para cautivar",
    social_events: "Eventos Sociales",
    social_events_desc:
      "Creamos celebraciones memorables: bodas de ensueño, XV años mágicos, bautizos especiales y más. Trabajamos por paquetes personalizados según tus necesidades.",
    corporate_events: "Eventos Corporativos",
    corporate_events_desc:
      "Fortalecemos tu marca con eventos profesionales de alto impacto. Desde conferencias hasta lanzamientos de productos.",
    process_title: "Nuestro Proceso",
    process_1: "Consulta inicial",
    process_2: "Diseño personalizado",
    process_3: "Coordinación detallada",
    process_4: "Ejecución perfecta",
    contact_hero_title: "Cuéntanos sobre tu evento",
    contact_hero_subtitle: "Estamos listos para escucharte y crear algo extraordinario",
    contact_form_title: "Envíanos un mensaje",
    form_name: "Nombre completo",
    form_email: "Correo electrónico",
    form_phone: "Teléfono",
    form_event_type: "Tipo de evento",
    form_message: "Cuéntanos sobre tu evento",
    form_message_placeholder: "Describe tu visión, fecha aproximada, número de invitados...",
    form_submit: "Enviar mensaje",
    form_sending: "Enviando...",
    form_success: "¡Mensaje enviado! Nos pondremos en contacto pronto.",
    event_social: "Evento Social",
    event_corporate: "Evento Corporativo",
    contact_info_title: "Contáctanos",
    contact_info_subtitle: "Estamos aquí para ti",
    phone: "Teléfono",
    email: "Correo Electrónico",
    follow_us: "Síguenos",
    footer_tagline: "Creando momentos eternos",
    footer_rights: "Todos los derechos reservados",
  },
  en: {
    home: "Home",
    about: "About",
    services: "Services",
    contact: "Contact",
    slogan: "Your Dream to Reality",
    hero_title: "Moments that last forever",
    hero_subtitle:
      "We transform your dreams into extraordinary events. We design unique experiences that capture the essence of every celebration.",
    hero_location_message:
      "No matter where you're from, we plan your event and bring it to life in El Salvador with the highest excellence.",
    hero_cta: "Start your story",
    hero_cta_secondary: "Discover our services",
    events_social: "Exclusive Social Events",
    events_corporate: "High-Impact Corporate Events",
    excellence: "Excellence in Every Detail",
    features_title: "Why choose us",
    features_subtitle:
      "We transform your vision into an unforgettable experience with exceptional planning and perfect execution",
    feature_1_title: "Professional Experience",
    feature_1_desc: "Years of experience creating memorable events with attention to detail and passion",
    feature_2_title: "Custom Design",
    feature_2_desc: "Every event is unique and designed specifically to reflect your vision and personality",
    feature_3_title: "Perfect Coordination",
    feature_3_desc: "Comprehensive management of all aspects so you can enjoy worry-free",
    cta_title: "Ready to create something extraordinary?",
    cta_subtitle: "Let's talk about your event and make your vision a reality",
    cta_button: "Contact now",
    about_hero_title: "Our Story",
    about_hero_subtitle: "Creating eternal moments with passion and dedication",
    our_story_badge: "Our Story",
    passion_title: "Our Passion",
    passion_desc: "Turning dreams into reality through meticulous planning and limitless creativity",
    no_borders_title: "Without Borders",
    commitment_title: "Our Commitment to You",
    commitment_1_title: "Personalized",
    commitment_1_desc: "Every event designed exclusively for you",
    commitment_2_title: "Availability",
    commitment_2_desc: "Constant support throughout the entire process",
    commitment_3_title: "Dedication",
    commitment_3_desc: "No limits in the pursuit of perfection",
    benefits_title: "The support you need for your perfect event",
    benefit_1_title: "Proven Experience",
    benefit_1_desc: "Professional planners with international vision and world-class standards",
    benefit_2_title: "Attention to Detail",
    benefit_2_desc: "Every element is carefully selected and coordinated to create perfect moments",
    benefit_3_title: "Flawless Execution",
    benefit_3_desc: "Smooth and professional coordination so you can enjoy without worries",
    story_title: "How Eternia was born",
    story_text:
      "Eternia was born from the dream of creating moments that transcend time. We always aspire to be more than event organizers; we want to be creators of unforgettable experiences. Every celebration is a unique opportunity to transform visions into reality, capturing the essence of the most significant moments and turning them into eternal memories.",
    values_title: "Our Values",
    value_1: "Excellence without limits",
    value_2: "Creativity and innovation",
    value_3: "Personalized dedication",
    value_4: "Unwavering commitment",
    services_hero_title: "Our Services",
    services_hero_subtitle: "Events designed to captivate",
    social_events: "Social Events",
    social_events_desc:
      "We create memorable celebrations: dream weddings, magical quinceañeras, special baptisms and more. We work with customized packages according to your needs.",
    corporate_events: "Corporate Events",
    corporate_events_desc:
      "We strengthen your brand with high-impact professional events. From conferences to product launches.",
    process_title: "Our Process",
    process_1: "Initial consultation",
    process_2: "Custom design",
    process_3: "Detailed coordination",
    process_4: "Perfect execution",
    contact_hero_title: "Let's talk about your event",
    contact_hero_subtitle: "We're ready to listen and create something extraordinary",
    contact_form_title: "Send us a message",
    form_name: "Full name",
    form_email: "Email address",
    form_phone: "Phone",
    form_event_type: "Event type",
    form_message: "Tell us about your event",
    form_message_placeholder: "Describe your vision, approximate date, number of guests...",
    form_submit: "Send message",
    form_sending: "Sending...",
    form_success: "Message sent! We'll be in touch soon.",
    event_social: "Social Event",
    event_corporate: "Corporate Event",
    contact_info_title: "Contact us",
    contact_info_subtitle: "We're here for you",
    phone: "Phone",
    email: "Email",
    follow_us: "Follow us",
    footer_tagline: "Creating eternal moments",
    footer_rights: "All rights reserved",
  },
  fr: {
    home: "Accueil",
    about: "À propos",
    services: "Services",
    contact: "Contact",
    slogan: "Votre Rêve Devient Réalité",
    hero_title: "Des moments qui durent pour toujours",
    hero_subtitle:
      "Nous transformons vos rêves en événements extraordinaires. Nous concevons des expériences uniques qui capturent l'essence de chaque célébration.",
    hero_location_message:
      "Peu importe d'où vous venez, nous planifions votre événement et le réalisons au Salvador avec la plus haute excellence.",
    hero_cta: "Commencez votre histoire",
    hero_cta_secondary: "Découvrez nos services",
    events_social: "Événements Sociaux Exclusifs",
    events_corporate: "Événements d'Entreprise à Fort Impact",
    excellence: "Excellence dans Chaque Détail",
    features_title: "Pourquoi nous choisir",
    features_subtitle:
      "Nous transformons votre vision en une expérience inoubliable avec une planification exceptionnelle et une exécution parfaite",
    feature_1_title: "Expérience Professionnelle",
    feature_1_desc: "Des années d'expérience créant des événements mémorables avec attention aux détails et passion",
    feature_2_title: "Design Personnalisé",
    feature_2_desc: "Chaque événement est unique et conçu spécifiquement pour refléter votre vision et personnalité",
    feature_3_title: "Coordination Parfaite",
    feature_3_desc: "Gestion complète de tous les aspects pour que vous profitiez sans soucis",
    cta_title: "Prêt à créer quelque chose d'extraordinaire?",
    cta_subtitle: "Parlons de votre événement et réalisons votre vision",
    cta_button: "Contactez maintenant",
    about_hero_title: "Notre Histoire",
    about_hero_subtitle: "Créer des moments éternels avec passion et dévouement",
    our_story_badge: "Notre Histoire",
    passion_title: "Notre Passion",
    passion_desc:
      "Transformer les rêves en réalité grâce à une planification méticuleuse et une créativité sans limites",
    no_borders_title: "Sans Frontières",
    commitment_title: "Notre Engagement Envers Vous",
    commitment_1_title: "Personnalisé",
    commitment_1_desc: "Chaque événement conçu exclusivement pour vous",
    commitment_2_title: "Disponibilité",
    commitment_2_desc: "Soutien constant tout au long du processus",
    commitment_3_title: "Dévouement",
    commitment_3_desc: "Sans limites dans la recherche de la perfection",
    benefits_title: "Le soutien dont vous avez besoin pour votre événement parfait",
    benefit_1_title: "Expérience Prouvée",
    benefit_1_desc: "Planificateurs professionnels avec vision internationale et standards de classe mondiale",
    benefit_2_title: "Attention aux Détails",
    benefit_2_desc: "Chaque élément est soigneusement sélectionné et coordonné pour créer des moments parfaits",
    benefit_3_title: "Exécution Impeccable",
    benefit_3_desc: "Coordination fluide et professionnelle pour que vous profitiez sans soucis",
    story_title: "Comment Eternia est né",
    story_text:
      "Eternia est né du rêve de créer des moments qui transcendent le temps. Nous aspirons toujours à être plus que des organisateurs d'événements; nous voulons être des créateurs d'expériences inoubliables. Chaque célébration est une opportunité unique de transformer des visions en réalité, capturant l'essence des moments les plus significatifs et les transformant en souvenirs éternels.",
    values_title: "Nos Valeurs",
    value_1: "Excellence sans limites",
    value_2: "Créativité et innovation",
    value_3: "Dévouement personnalisé",
    value_4: "Engagement inébranlable",
    services_hero_title: "Nos Services",
    services_hero_subtitle: "Des événements conçus pour captiver",
    social_events: "Événements Sociaux",
    social_events_desc:
      "Nous créons des célébrations mémorables: mariages de rêve, quinceañeras magiques, baptêmes spéciaux et plus. Nous travaillons avec des forfaits personnalisés selon vos besoins.",
    corporate_events: "Événements d'Entreprise",
    corporate_events_desc:
      "Nous renforçons votre marque avec des événements professionnels à fort impact. Des conférences aux lancements de produits.",
    process_title: "Notre Processus",
    process_1: "Consultation initiale",
    process_2: "Design personnalisé",
    process_3: "Coordination détaillée",
    process_4: "Exécution parfaite",
    contact_hero_title: "Parlons de votre événement",
    contact_hero_subtitle: "Nous sommes prêts à écouter et créer quelque chose d'extraordinaire",
    contact_form_title: "Envoyez-nous un message",
    form_name: "Nom complet",
    form_email: "Adresse e-mail",
    form_phone: "Téléphone",
    form_event_type: "Type d'événement",
    form_message: "Parlez-nous de votre événement",
    form_message_placeholder: "Décrivez votre vision, date approximative, nombre d'invités...",
    form_submit: "Envoyer le message",
    form_sending: "Envoi...",
    form_success: "Message envoyé! Nous vous contacterons bientôt.",
    event_social: "Événement Social",
    event_corporate: "Événement d'Entreprise",
    contact_info_title: "Contactez-nous",
    contact_info_subtitle: "Nous sommes là pour vous",
    phone: "Téléphone",
    email: "E-mail",
    follow_us: "Suivez-nous",
    footer_tagline: "Créer des moments éternels",
    footer_rights: "Tous droits réservés",
  },
  pt: {
    home: "Início",
    about: "Sobre nós",
    services: "Serviços",
    contact: "Contato",
    slogan: "Seu Sonho se Torna Realidade",
    hero_title: "Momentos que duram para sempre",
    hero_subtitle:
      "Transformamos seus sonhos em eventos extraordinários. Projetamos experiências únicas que capturam a essência de cada celebração.",
    hero_location_message:
      "Não importa de onde você é, planejamos seu evento e o realizamos em El Salvador com a máxima excelência.",
    hero_cta: "Comece sua história",
    hero_cta_secondary: "Descubra nossos serviços",
    events_social: "Eventos Sociais Exclusivos",
    events_corporate: "Eventos Corporativos de Alto Impacto",
    excellence: "Excelência em Cada Detalhe",
    features_title: "Por que nos escolher",
    features_subtitle:
      "Transformamos sua visão em uma experiência inesquecível com planejamento excepcional e execução perfeita",
    feature_1_title: "Experiência Profissional",
    feature_1_desc: "Anos de experiência criando eventos memoráveis com atenção aos detalhes e paixão",
    feature_2_title: "Design Personalizado",
    feature_2_desc: "Cada evento é único e projetado especificamente para refletir sua visão e personalidade",
    feature_3_title: "Coordenação Perfeita",
    feature_3_desc: "Gestão abrangente de todos os aspectos para que você aproveite sem preocupações",
    cta_title: "Pronto para criar algo extraordinário?",
    cta_subtitle: "Vamos conversar sobre seu evento e tornar sua visão realidade",
    cta_button: "Contatar agora",
    about_hero_title: "Nossa História",
    about_hero_subtitle: "Criando momentos eternos com paixão e dedicação",
    our_story_badge: "Nossa História",
    passion_title: "Nossa Paixão",
    passion_desc: "Transformar sonhos em realidade através de planejamento meticuloso e criatividade sem limites",
    no_borders_title: "Sem Fronteiras",
    commitment_title: "Nosso Compromisso com Você",
    commitment_1_title: "Personalizado",
    commitment_1_desc: "Cada evento projetado exclusivamente para você",
    commitment_2_title: "Disponibilidade",
    commitment_2_desc: "Apoio constante durante todo o processo",
    commitment_3_title: "Dedicação",
    commitment_3_desc: "Sem limites na busca da perfeição",
    benefits_title: "O suporte que você precisa para seu evento perfeito",
    benefit_1_title: "Experiência Comprovada",
    benefit_1_desc: "Planejadores profissionais com visão internacional e padrões de classe mundial",
    benefit_2_title: "Atenção aos Detalhes",
    benefit_2_desc: "Cada elemento é cuidadosamente selecionado e coordenado para criar momentos perfeitos",
    benefit_3_title: "Execução Impecável",
    benefit_3_desc: "Coordenação fluida e profissional para que você aproveite sem preocupações",
    story_title: "Como nasceu Eternia",
    story_text:
      "Eternia nasceu do sonho de criar momentos que transcendem o tempo. Sempre aspiramos a ser mais do que organizadores de eventos; queremos ser criadores de experiências inesquecíveis. Cada celebração é uma oportunidade única para transformar visões em realidade, capturando a essência dos momentos mais significativos e transformando-os em memórias eternas.",
    values_title: "Nossos Valores",
    value_1: "Excelência sem limites",
    value_2: "Criatividade e inovação",
    value_3: "Dedicação personalizada",
    value_4: "Compromisso inabalável",
    services_hero_title: "Nossos Serviços",
    services_hero_subtitle: "Eventos projetados para cativar",
    social_events: "Eventos Sociais",
    social_events_desc:
      "Criamos celebrações memoráveis: casamentos de sonho, quinceañeras mágicas, batizados especiais e mais. Trabalhamos com pacotes personalizados de acordo com suas necessidades.",
    corporate_events: "Eventos Corporativos",
    corporate_events_desc:
      "Fortalecemos sua marca com eventos profissionais de alto impacto. De conferências a lançamentos de produtos.",
    process_title: "Nosso Processo",
    process_1: "Consulta inicial",
    process_2: "Design personalizado",
    process_3: "Coordenação detalhada",
    process_4: "Execução perfeita",
    contact_hero_title: "Vamos falar sobre seu evento",
    contact_hero_subtitle: "Estamos prontos para ouvir e criar algo extraordinário",
    contact_form_title: "Envie-nos uma mensagem",
    form_name: "Nome completo",
    form_email: "Endereço de e-mail",
    form_phone: "Telefone",
    form_event_type: "Tipo de evento",
    form_message: "Conte-nos sobre seu evento",
    form_message_placeholder: "Descreva sua visão, data aproximada, número de convidados...",
    form_submit: "Enviar mensagem",
    form_sending: "Enviando...",
    form_success: "Mensagem enviada! Entraremos em contato em breve.",
    event_social: "Evento Social",
    event_corporate: "Evento Corporativo",
    contact_info_title: "Entre em contato",
    contact_info_subtitle: "Estamos aqui para você",
    phone: "Telefone",
    email: "E-mail",
    follow_us: "Siga-nos",
    footer_tagline: "Criando momentos eternos",
    footer_rights: "Todos os direitos reservados",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("es")

  useEffect(() => {
    const saved = localStorage.getItem("eternia-language") as Language
    if (saved && ["es", "en", "fr", "pt"].includes(saved)) {
      setLanguage(saved)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("eternia-language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
